clear
fir_scaling_dat
%t = [1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105];
t = [1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100];
figure('units','inches')
pos = get(gcf,'pos');
set(gcf,'pos',[pos(1) pos(2) 16 4])
% errorbar(t, NON_LI_0_REG, NON_LI_0_REG_min-NON_LI_0_REG,NON_LI_0_REG_max-NON_LI_0_REG ,':v',...
%     'Color', 'r',...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor','r')
% hold on
% errorbar(t, NON_LI_3_REG,NON_LI_3_REG_min-NON_LI_3_REG,NON_LI_3_REG_max-NON_LI_3_REG, '--v',...
%     'Color', 'r',...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor','r')
% hold on
% errorbar(t, NON_LI_6_REG,NON_LI_6_REG_min-NON_LI_6_REG,NON_LI_6_REG_max-NON_LI_6_REG, '-v',...
%     'Color', 'r',...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor','r')
% hold on
% errorbar(t, LI_CREDIT_0,LI_CREDIT_0_min-LI_CREDIT_0,LI_CREDIT_0_max-LI_CREDIT_0, ':d',...
%     'Color', 'b',...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor','b')
% hold on
% errorbar(t, LI_CREDIT_3,LI_CREDIT_3_min-LI_CREDIT_3,LI_CREDIT_3_max-LI_CREDIT_3, '--d',...
%     'Color', 'b',...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor','b')
% hold on
% errorbar(t, LI_CREDIT_6,LI_CREDIT_6_min-LI_CREDIT_6,LI_CREDIT_6_max-LI_CREDIT_6, '-d',...
%     'Color', 'b',...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor','b')
% hold on
% errorbar(t, LI_QSYS_0,LI_QSYS_0_min-LI_QSYS_0,LI_QSYS_0_max-LI_QSYS_0, ':s',...
%     'Color', 'g',...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor','g')
% hold on
% errorbar(t, LI_QSYS_3,LI_QSYS_3_min-LI_QSYS_3,LI_QSYS_3_max-LI_QSYS_3, '--s',...
%     'Color', 'g',...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor','g')
% hold on
% errorbar(t, LI_QSYS_6,LI_QSYS_6_min-LI_QSYS_6,LI_QSYS_6_max-LI_QSYS_6, '-d',...
%     'Color', 'g',...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor','g')
subplot(1,3,1)
plot(t, NON_LI_0_REG,':v',...
    'Color', 'r',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','r')
hold on
plot(t, LI_CREDIT_0, ':d',...
    'Color', 'b',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','b')
hold on
plot(t, LI_QSYS_0, ':s',...
    'Color', 'g',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','g')
hold on
plot(t, LI_CARLONI_0, ':o',...
    'Color', 'k',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','k')
legend('NON-LI 0 REG', ...
       'LI CREDIT 0 REG', ...
       'LI QSYS 0 REG', ...
       'LI CARLONI 0 RS', ...
       'Location','southWest')
xlabel('Number of FIR Instances'), ylabel('Fmax [MHz]')
title('No Interconnect pipelining')
ylim([min(ylim) 550])

subplot(1,3,2)
plot(t, NON_LI_3_REG, '--v',...
    'Color', 'r',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','r')
hold on
plot(t, LI_CREDIT_3, '--d',...
    'Color', 'b',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','b')
hold on
plot(t, LI_QSYS_3, '--s',...
    'Color', 'g',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','g')
hold on
plot(t, LI_CARLONI_1, '--o',...
    'Color', 'k',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','k')
legend('NON-LI 3 REG', ...
       'LI CREDIT 3 REG', ...
       'LI QSYS 3 REG', ...
       'LI CARLONI 1 RS', ...
       'Location','southWest')
xlabel('Number of FIR Instances'), ylabel('Fmax [MHz]')
title('Three Stage pipelining')
ylim([min(ylim) 550])

subplot(1,3,3)
plot(t, NON_LI_6_REG, '-v',...
    'Color', 'r',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','r')
hold on
plot(t, LI_CREDIT_6, '-d',...
    'Color', 'b',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','b')
hold on
plot(t, LI_QSYS_6, '-s',...
    'Color', 'g',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','g')
hold on
plot(t, LI_CARLONI_2, '-o',...
    'Color', 'k',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','k')
legend('NON-LI 6 REG', ...
       'LI CREDIT 6 REG', ...
       'LI QSYS 6 REG', ...
       'LI CARLONI 2 RS', ...
       'Location','southWest')
xlabel('Number of FIR Instances'), ylabel('Fmax [MHz]')
title('Six Stage pipelining')
ylim([min(ylim) 550])
%xlim([0 110])
print('fir_frequency_scaling', '-dpng')
% print('fir_frequency_scaling','-depsc')
